n_arms: 8
n_ensemble: 16
p_bootstrap: 0.5
change_freq: 2000
batch_size: 64
n_episodes: 2

learning_rate:
    type: constant

    constant: 
        value: 0.05

epsilon:
    type: constant

    constant:
        value: 0.2

distribution_mean_range: [-3, 3]
distribution_scale_range: [-3, 3]