seed: 4

n_arms: 8
n_ensemble: 16
p_bootstrap: 0.5
change_freq: 10000
test_frequency: 50
num_test_samples: 1000
batch_size: 64
n_episodes: 2

optimiser: sgd
action_selection: softmax

adam:
    alpha: 0.05
    beta_1: 0.9
    beta_2: 0.999
    epsilon: 0.00000001

rms_prop:
    eta: 0.01
    gamma: 0.9
    epsilon: 0.00000001

learning_rate:

    default_lr: 0.05 

    type: constant

    constant: 
        value: 0.1

    linear_decay:
        initial_lr: 1
        final_lr: 0.1
        lr_decay: 0.0001

    modulate:
        factor: 0.1

epsilon:

    minimum_eps: 0
    default_eps: 0.2

    type: constant

    constant:
        value: 1

    linear_decay:
        initial_eps: 1
        final_eps: 0.1
        eps_decay: 0.0001

beta:

    minimum_beta: 0
    default_beta: 0.2

    type: constant

    constant:
        value: 1000

    linear_decay:
        initial_beta: 1
        final_beta: 0.1
        beta_decay: 0.0001

ucb:
    ucb_constant: 10

discounted_ucb:
    ucb_gamma: 0.99
    ucb_epsilon: 0.5
    ucb_constant: 1

distribution_mean_range: [-3, 3]
distribution_std_range: [0.03, 1.7]