n_arms: 8
n_ensemble: 16
p_bootstrap: 0.5
change_freq: 2000
batch_size: 64
n_episodes: 2
learning_rate: 0.05
epsilon: 0.2

modulate_lr:
modulate_eps:

distribution_mean_range: [-3, 3]
distribution_scale_range: [-3, 3]